#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 03 11:49:45 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_digital_lock_behav -key {Behavioral:sim_1:Functional:tb_digital_lock} -tclbatch tb_digital_lock.tcl -view /home/it/DigitalSystemDesign/Lab7/digital_lock/tb_digital_lock_behav.wcfg -log simulate.log"
xsim tb_digital_lock_behav -key {Behavioral:sim_1:Functional:tb_digital_lock} -tclbatch tb_digital_lock.tcl -view /home/it/DigitalSystemDesign/Lab7/digital_lock/tb_digital_lock_behav.wcfg -log simulate.log

